name: deepsensorgallery
channels:
  - pytorch
  - nvidia
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - pytorch-cuda=11.7
  - cartopy
  - jupyter
  - seaborn=0.12.2
  - pip
  - pip:
    - deepsensor

