name: deepsensorgallery
channels:
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - cartopy
  - jupyter
  - seaborn=0.12.2
  - pip
  - pip:
    - deepsensor
    - git+https://github.com/magnusross/get-station-data.git

